apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper-example
  name: zookeeper-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zookeeper-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper-example
    spec:
      containers:
      - image: penghuiping/zookeeper-example
        name: zookeeper-example
        resources:
          requests:
            memory: 256M #内存256M
            cpu: 1000m #1个cpu
          limits:
            memory: 512M
            cpu: 2000m
        livenessProbe: ## 健康检查，重启可以解决
          initialDelaySeconds: 60 #第一次健康检查的时间，需要晚于容器启动时间
          httpGet:
              port: 8080
              path: /actuator/health
        readinessProbe: ## 启动以后，什么时候容器准备好可以处理外部请求
          httpGet:
              port: 8080
              path: /actuator/health
status: {}

